name: Diffusc (path mode)

on:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'
  pull_request:
    branches: [ main, dev ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - name: Safemoon
            out: ./contracts/test/safemoon/
            args: ./diffusc/tests/test_data/safemoon/SafemoonV2.sol ./diffusc/tests/test_data/safemoon/SafemoonV3.sol -p ./diffusc/tests/test_data/safemoon/TransparentProxyTestHarness.sol -V 0.8.11 --run-custom ./contracts/test/safemoon/DiffFuzzCustomInit.sol DiffFuzzInit

          - name: Compound
            out: ./contracts/test/compound
            args: ./contracts/implementation/compound/compound-0.8.10/ComptrollerHarnessV1.sol ./contracts/implementation/compound/compound-0.8.10/ComptrollerHarnessV2.sol -t ./contracts/implementation/compound/compound-0.8.10/CErc20.sol,./contracts/implementation/compound/compound-0.8.10/CompHarness.sol -p ./contracts/implementation/compound/compound-0.8.10/Unitroller.sol -u -V 0.8.10 --run-custom ./contracts/test/compound/DiffFuzzCustomInit.sol DiffFuzzCustomInit

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install diffusc
      run: |
        pip3 install .
        solc-select install 0.8.11
        solc-select use 0.8.11

    - name: Run diffusc
      id: prepare
      run: |
        diffusc ${{ matrix.args }} -d ${{ matrix.out }} -L 200000 -r --first-failure